language: node_js
node_js:
- '5'
script:
- gulp lint docs release
- npm start &
- sleep 5
- karma start
env:
  global:
  - secure: ONX4S6726nQH107YhcYsTJzH4uQDGTpSjPb33hzYT6Jv+9FBo81mcae20+zt+7AuresNXN2e/Mx6kkEooAPIa0DvMHfGu+7SPnG1yeAJVZzIJvanvYqnyMEcLbJgy09aqP8FqrW+EZAFoE5Oh1zxQqr59e/u1i3hvLdIbGE7AWM=
  - secure: Og26Aq8tfmpvZAXPdPYFLa8bGSttCI3bJTwLcJgbjwBNdX9lwNO4XTshyNM6Vp2h6JScQY2oq1gwu5ufcDOVbj9qzbkpgrGsm0MlX1FkSTPVlIrXNdU3/S7a8GXLxpmOSxiBxS/yZd8ReoY9B9rayW2HY4ffCVAM96XbptngZ98=
