site_name: TerriaJS
#cosmo|cyborg|readthedocs|yeti|journal|bootstrap|readable|united|simplex|flatly|spacelab|amelia|cerulean|slate|mkdocs
theme: readthedocs
docs_dir: 'doc'
site_dir: '../wwwroot/doc/guide'
#strict: true
pages:
- Home: 'README.md'
- Getting Started: 'getting-started.md'
- Customizing:
    - Overview: 'customizing/README.md'
    - Client-side Config: 'customizing/client-side-config.md'
    - Initialization Files: 'customizing/initialization-files.md'
    - Server-side Config: 'customizing/server-side-config.md'
    - Skinning: 'customizing/skinning.md'
- Connecting to Data:
    - Overview: 'connecting-to-data/README.md'
    - Cross-Origin Resource Sharing: 'connecting-to-data/cross-origin-resource-sharing.md'
    - Catalog Groups: 'connecting-to-data/catalog-groups.md'
    - Catalog Items: 'connecting-to-data/catalog-items.md'
    - Catalog Functions: 'connecting-to-data/catalog-functions.md'
    - Catalog Type Details:
        - ABS ITT: 'connecting-to-data/catalog-type-details/abs-itt.md'
        - Bing Maps: 'connecting-to-data/catalog-type-details/bing-maps.md'
        - CKAN Resource: 'connecting-to-data/catalog-type-details/ckan-resource.md'
        # - Composite: 'connecting-to-data/catalog-type-details/composite.md'
        - Comma-Separated Values (CSV): 'connecting-to-data/catalog-type-details/csv.md'
        - Cesium Terrain: 'connecting-to-data/catalog-type-details/cesium-terrain.md'
        - Cesium Language (CZML): 'connecting-to-data/catalog-type-details/czml.md'
        - ArcGIS FeatureServer: 'connecting-to-data/catalog-type-details/esri-featureServer.md'
        - ArcGIS MapServer: 'connecting-to-data/catalog-type-details/esri-mapServer.md'
        - GeoJSON: 'connecting-to-data/catalog-type-details/geojson.md'
        - GPX: 'connecting-to-data/catalog-type-details/gpx.md'
        - Keyhole Markup Language (KML): 'connecting-to-data/catalog-type-details/kml.md'
        - Format Conversion Service (based on OGR): 'connecting-to-data/catalog-type-details/ogr.md'
        - OpenStreetMap: 'connecting-to-data/catalog-type-details/open-street-map.md'
        - SDMX-JSON: 'connecting-to-data/catalog-type-details/sdmx-json.md'
        - Sensor Observation Service (SOS): 'connecting-to-data/catalog-type-details/sos.md'
        - URL Template: 'connecting-to-data/catalog-type-details/url-template.md'
        - Web Feature Service (WFS): 'connecting-to-data/catalog-type-details/wfs.md'
        - Web Map Service (WMS): 'connecting-to-data/catalog-type-details/wms.md'
- Deploying:
    - Overview: 'deploying/README.md'
    - Deploying TerriaMap: 'deploying/deploying-terriamap.md'
    - Deploying to AWS: 'deploying/deploying-to-aws.md'
    - Deploying with Docker: 'deploying/deploying-with-docker.md'
    - Setting Up a Region Mapping Server: 'deploying/setting-up-a-region-mapping-server.md'
    - Setting Up Geoserver: 'deploying/setting-up-geoserver.md'
    - Using as a CKAN Previewer: 'deploying/using-as-a-ckan-previewer.md'
    - Controlling with URL Parameters: 'deploying/controlling-with-url-parameters.md'
    - Controlling in an &lt;iframe&gt; or Popup: 'deploying/controlling-in-an-iframe-or-popup.md'
- Contributing:
    - Overview: 'contributing/README.md'
    - Development Environment: 'contributing/development-environment.md'
    - Using a Custom Version of Cesium: 'contributing/using-a-custom-version-of-cesium.md'
    - Setting up Saucelabs: 'contributing/setting-up-saucelabs.md'
    - Problems and Solutions: 'contributing/problems-and-solutions.md'
