site_name: TerriaJS
#cosmo|cyborg|readthedocs|yeti|journal|bootstrap|readable|united|simplex|flatly|spacelab|amelia|cerulean|slate|mkdocs
theme: readthedocs
docs_dir: 'Documentation'
site_dir: '../wwwroot/user-guide'
pages:
- Home: 'index.md'
- Getting Started: 'GettingStarted/index.md'
- Deployment:
    - Overview: 'Deployment/index.md'
    - Deploying TerriaMap: 'Deployment/Deploying-Terria-Map.md'
- Customizing:
    - Overview: 'Customizing/index.md'
    - Config JSON: 'Customizing/Config-JSON.md'
- Contributors:
    - Development Environment: 'Contributors/Development-environment.md'